"""Master build entrypoint for the LEGOLAND California world.

Usage (inside ./.venv, Python 3.12):
    python -m src.build info                 # print resolved config (verify version/formats)
    python -m src.build all                  # regenerate the whole world + packs into build/
    python -m src.build world                # run a single phase
    python -m src.build validate             # structural validation suite
    python -m src.build clean                # remove the output dir

Design rules (from the brief):
  * Always generate into a CLEAN output dir; never write into a live save.
  * Idempotent + resumable; a rerun reproduces the world.
  * One controlled interpreter (Python 3.12); refuse others unless --allow-any-python.
"""
from __future__ import annotations

import argparse
import importlib
import logging
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

from . import config as cfg

LOG = logging.getLogger("legoland")
REQUIRED_PY = (3, 12)
OUTPUT_SENTINEL = ".legoland-build"  # marks a dir as ours, safe to overwrite

# phase name -> module providing run(ctx). "package" is handled in-process below.
PHASE_MODULES = {
    "world": "src.world",
    "terrain": "src.terrain",
    "rail": "src.rail",
    "structures": "src.structures",
    "rides": "src.entities",
    "datapack": "src.datapack",
    "resourcepack": "src.resourcepack",
    "validate": "src.validate",
}
# Order for `all`. Structures run BEFORE rail so the coaster corridor (incl. station
# boarding cells) is laid last and is never buried/erased by a structure's flatten —
# the line must stay rideable. `finalize` strips amulet artifacts; `package` zips; `validate` last.
ALL_SEQUENCE = ["world", "terrain", "structures", "rail", "rides",
                "datapack", "resourcepack", "finalize", "package", "validate"]


@dataclass
class BuildContext:
    out_dir: Path
    config_dir: Path
    version: cfg.VersionConfig
    transform: dict
    lands: dict
    rides: dict
    jobs: int = 1
    resume: bool = False
    force: bool = False

    @property
    def world_dir(self) -> Path:
        return self.out_dir / "world"

    @property
    def datapack_out(self) -> Path:
        # In singleplayer the datapack lives inside the world save.
        return self.world_dir / "datapacks" / "legoland"

    @property
    def resourcepack_out(self) -> Path:
        return self.out_dir / "resourcepack"


def _check_python(allow_any: bool) -> None:
    if sys.version_info[:2] != REQUIRED_PY and not allow_any:
        sys.exit(
            f"ERROR: requires Python {REQUIRED_PY[0]}.{REQUIRED_PY[1]} "
            f"(got {sys.version.split()[0]}). Activate ./.venv or pass --allow-any-python."
        )


def _setup_logging(level: str) -> None:
    logging.basicConfig(
        level=getattr(logging, level.upper(), logging.INFO),
        format="%(asctime)s %(levelname)-7s %(name)s | %(message)s",
        datefmt="%H:%M:%S",
    )


def make_context(args) -> BuildContext:
    config_dir = Path(args.config_dir)
    return BuildContext(
        out_dir=Path(args.out),
        config_dir=config_dir,
        version=cfg.load_version(config_dir),
        transform=cfg.load_transform(config_dir),
        lands=cfg.load_lands(config_dir),
        rides=cfg.load_rides(config_dir),
        jobs=args.jobs,
        resume=args.resume,
        force=args.force,
    )


def prepare_output_dir(ctx: BuildContext) -> None:
    """Guarantee a clean output dir that is unmistakably ours (never a live save)."""
    out = ctx.out_dir
    if out.exists():
        sentinel = out / OUTPUT_SENTINEL
        looks_like_save = (out / "world" / "level.dat").exists() or (out / "level.dat").exists()
        if not sentinel.exists() and looks_like_save and not ctx.force:
            sys.exit(
                f"REFUSING to overwrite {out}: looks like an existing save and lacks "
                f"the {OUTPUT_SENTINEL} marker. Pass --force only if you are certain."
            )
        if not ctx.resume:
            LOG.info("clearing output dir %s", out)
            shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)
    (out / OUTPUT_SENTINEL).write_text("Generated by src.build — safe to delete.\n")


def _run_phase(name: str, ctx: BuildContext) -> None:
    if name == "package":
        return _phase_package(ctx)
    if name == "finalize":
        return _phase_finalize(ctx)
    module_path = PHASE_MODULES[name]
    mod = importlib.import_module(module_path)
    if not hasattr(mod, "run"):
        raise SystemExit(f"phase '{name}' ({module_path}) has no run(ctx)")
    LOG.info("=== phase: %s ===", name)
    mod.run(ctx)


def _phase_finalize(ctx: BuildContext) -> None:
    """Strip amulet/runtime artifacts the Minecraft client can't use.

    amulet writes entities/*.mca chunks that 26.1.2 rejects (missing Position); we place no
    pre-placed entities (ride rigs are datapack-summoned), so delete entities/ and let MC
    recreate them. Also drop the session lock / progress / .DS_Store from the save.
    """
    # 1) find a grass spawn near the park entrance, then REBUILD the authoritative level.dat
    #    with it. Rebuilding (vs patching) guarantees a deterministic level.dat (no amulet
    #    LastPlayed timestamp) and that all kid-safe fields survive amulet's chunk saves.
    if (ctx.world_dir / "level.dat").exists() and (ctx.world_dir / "region").exists():
        from .world import find_ground_spawn
        from .world.level_dat import write_level_dat
        spawn = find_ground_spawn(ctx)
        write_level_dat(ctx, spawn=spawn)

    # 2) strip artifacts (entities/ recreated by amulet but rejected by 26.1.2; lock files)
    wd = ctx.world_dir
    removed = []
    for name in ("entities", "entities 2"):
        p = wd / name
        if p.exists():
            shutil.rmtree(p)
            removed.append(name + "/")
    for name in ("session.lock", ".legoland_terrain_progress", ".DS_Store"):
        p = wd / name
        if p.exists():
            p.unlink()
            removed.append(name)
    LOG.info("finalize: removed %s", ", ".join(removed) or "(nothing to remove)")


def _zip_dir(src: Path, zip_path: Path, arc_root: str = "",
             exclude_files=frozenset(), exclude_dirs=frozenset()) -> int:
    import zipfile
    count = 0
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for p in sorted(src.rglob("*")):
            if p.is_dir():
                if p.name in exclude_dirs:
                    continue
                continue
            if any(part in exclude_dirs for part in p.relative_to(src).parts):
                continue
            if p.name in exclude_files:
                continue
            rel = p.relative_to(src)
            arc = f"{arc_root}/{rel}" if arc_root else str(rel)
            zf.write(p, arc)
            count += 1
    return count


INSTALL_MD = """# Install — LEGOLAND California

A private family Minecraft Java world. Built for client **{client}** (the world is written
at {world_patch} and upgrades automatically on first load — this is expected).

## 1. The world (includes the datapack)
1. Unzip `LegolandCalifornia-world.zip`.
2. Move the `LEGOLAND California` folder into your Minecraft `saves/` folder:
   `~/Library/Application Support/minecraft/saves/` (macOS).
3. Launch Minecraft **{client}**, open the world ("LEGOLAND California"). It loads in Creative.

## 2. The resource pack (optional theming)
1. Copy `LegolandCalifornia-resourcepack.zip` into `resourcepacks/`.
2. In game: Options → Resource Packs → enable "LEGOLAND California".

## 3. Ride the coasters!
- You spawn at **The Beginning** (the park entrance).
- Type `/function legoland:menu` (chat) — a clickable menu appears.
- Click **Ride a coaster** → pick one (The Dragon to start).
- You hop into the coaster train on the track and ride. Click **Exit ride** to stop.
- **Travel to a land** in the menu teleports you around the park.

It is always bright, sunny, peaceful, Creative — safe for young explorers.

See TESTING.md for what to check / report. Private/family build — please don't redistribute.
"""


def _phase_package(ctx: BuildContext) -> None:
    """Zip the world (with datapack inside) + the resource pack; write INSTALL.md."""
    dist = ctx.out_dir / "dist"
    dist.mkdir(parents=True, exist_ok=True)

    world_zip = dist / "LegolandCalifornia-world.zip"
    n1 = _zip_dir(ctx.world_dir, world_zip, arc_root="LEGOLAND California",
                  exclude_files={"session.lock", ".legoland_terrain_progress", ".DS_Store"},
                  exclude_dirs={"entities", "entities 2"})

    rp_zip = dist / "LegolandCalifornia-resourcepack.zip"
    n2 = _zip_dir(ctx.resourcepack_out, rp_zip, arc_root="",
                  exclude_files={".DS_Store"})

    install = INSTALL_MD.format(client=ctx.version.client_patch, world_patch=ctx.version.patch)
    (dist / "INSTALL.md").write_text(install)
    (Path("docs") / "INSTALL.md").write_text(install)
    LOG.info("package: world.zip (%d files) + resourcepack.zip (%d files) -> %s", n1, n2, dist)


# --------------------------------------------------------------------------- #
# subcommands
# --------------------------------------------------------------------------- #
def cmd_info(ctx: BuildContext) -> None:
    v = ctx.version
    print("LEGOLAND California — resolved config")
    print(f"  world save version  : {v.patch}  DataVersion {v.data_version} (amulet output; client upgrades it)")
    print(f"  amulet game_version : {v.platform} {v.game_version}")
    print(f"  client version      : {v.client_patch}  DataVersion {v.client_data_version} (packs target this)")
    print(f"  datapack pack_format: {v.datapack_format}.{v.datapack_minor}")
    print(f"  resourcepack format : {v.resourcepack_format}.{v.resourcepack_minor}")
    tr = ctx.transform
    park = tr.get("park", {})
    scale = tr.get("scale", {})
    print(f"  park footprint      : ~{scale.get('park_blocks', '?')} blocks across "
          f"(compression {scale.get('compression_factor', '?')} m/block, "
          f"vert exag {scale.get('vertical_exaggeration', '?')}x)")
    print(f"  anchors             : {len(tr.get('anchor', []))} GPS pins")
    lands_list = cfg.lands(ctx.lands)
    mvp = cfg.mvp_lands(ctx.lands)
    print(f"  lands               : {len(lands_list)} total, {len(mvp)} MVP "
          f"-> {', '.join(l['name'] for l in lands_list)}")
    coasters = cfg.coasters(ctx.rides)
    statics = cfg.static_rides(ctx.rides)
    print(f"  coasters (rail)     : {len(coasters)} -> {', '.join(c['name'] for c in coasters)}")
    print(f"  static rides        : {len(statics)}")
    print(f"  output dir          : {ctx.out_dir}")


def cmd_clean(ctx: BuildContext) -> None:
    if ctx.out_dir.exists():
        LOG.info("removing %s", ctx.out_dir)
        shutil.rmtree(ctx.out_dir)
    else:
        LOG.info("%s does not exist; nothing to clean", ctx.out_dir)


def cmd_all(ctx: BuildContext) -> None:
    prepare_output_dir(ctx)
    for name in ALL_SEQUENCE:
        _run_phase(name, ctx)
    LOG.info("=== build complete -> %s ===", ctx.out_dir)


def cmd_phase(ctx: BuildContext, name: str) -> None:
    # single phases that produce world data ensure the output dir exists first
    if name in ("world",) and not ctx.world_dir.exists():
        prepare_output_dir(ctx)
    _run_phase(name, ctx)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="src.build", description="Regenerate the LEGOLAND California world.")
    p.add_argument("--out", default="build", help="output directory (default: build)")
    p.add_argument("--config-dir", default="config", help="config directory (default: config)")
    p.add_argument("--jobs", type=int, default=1, help="worker count for region-batched phases")
    p.add_argument("--resume", action="store_true", help="resume into an existing output dir")
    p.add_argument("--force", action="store_true", help="override the live-save safety check")
    p.add_argument("--log-level", default="INFO", help="DEBUG/INFO/WARNING/ERROR")
    p.add_argument("--allow-any-python", action="store_true", help=argparse.SUPPRESS)

    sub = p.add_subparsers(dest="command", required=True)
    sub.add_parser("info", help="print resolved config and exit")
    sub.add_parser("clean", help="remove the output dir")
    sub.add_parser("all", help="run every phase in order")
    for name in [*PHASE_MODULES.keys(), "finalize", "package"]:
        sub.add_parser(name, help=f"run the '{name}' phase")
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    _setup_logging(args.log_level)
    _check_python(args.allow_any_python)

    ctx = make_context(args)
    cmd = args.command
    if cmd == "info":
        cmd_info(ctx)
    elif cmd == "clean":
        cmd_clean(ctx)
    elif cmd == "all":
        cmd_all(ctx)
    else:
        cmd_phase(ctx, cmd)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
